### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by serhii-londar** [novi/MagickWand-OSX#1]
Hi. Can you explain this line:

https://github.com/novi/MagickWand-OSX/blob/95e943a0a8f45f8d82aa558c51d5c2c1e12904fd/module.modulemap#L3

Thanks in advance!

**Comment by novi** [comment]
It makes Swift linker link MagickWand dynamic library(may be `libMagickWand-6.Q16.dylib` ) on your system.
Follow [Usage.md](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md) of Package Manager.
